import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import type { Locale } from "@/libs/next-intl";
import { ClientProvider,ServerProvider } from "@/providers/";

export const metadata = {
  title: "Create Devviantex App",
  description: "Generated by extended version of create-t3-app by Devviantex",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type InnerRootLayoutProps = {
  children: React.ReactNode;
  params: { locale: Locale };
};

const InnerRootLayout = ({ children, params: { locale } }: InnerRootLayoutProps) => {
  return (
    <html className={`${GeistSans.variable}`} lang={locale}>
      <body>
        <ServerProvider locale={locale}>
          <ClientProvider>{children}</ClientProvider>
        </ServerProvider>
      </body>
    </html>
  );
};

export default InnerRootLayout;
